### ISSUE TITLE
Microsoft Azure Insights

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-opentelemetry-exporter#33]
Azure Insights is an OpenTelemetry sever for Azure

There is this JAR but was hoping we could just switch easily between Jaeager locally and Azure in the environment.

Looks like MS has an exporter available: https://learn.microsoft.com/en-us/java/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-java-preview

```xml
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-monitor-opentelemetry-exporter</artifactId>
  <version>1.0.0-beta.8</version>
</dependency>
```

**Comment by melloware** [comment]
There is also this from OpenTelemetry itself: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter

**Comment by trask** [comment]
hey @melloware! I'm from the Azure Monitor Java team. Were you able to get things working with the Azure Monitor OpenTelemetry Exporter? Also, are you using native images (we are working on supporting that currently).

cc @jeanbisutti @heyams

**Comment by melloware** [comment]
That is great news! No I was waiting to hear back right now I use Quarkus open telemetry and Jaeger locally but would love to publish to Azure when deploying my app to AKS!  

Do you have anything I can try?

**Comment by melloware** [comment]
Also not sure if you were aware of this Quarkiverse project supporting Azure services https://github.com/quarkiverse/quarkus-azure-services

Not sure if the azure monitor plug-in belongs there or in this extension.

**Comment by brunobat** [comment]
We should add the exporter here similarly to what happens with the Micrometer registries: https://github.com/quarkiverse/quarkus-micrometer-registry

**Comment by brunobat** [comment]
Will be working on this.

**Comment by melloware** [comment]
Awesome work!

**Comment by jeanbisutti** [comment]
@melloware Have you tried to deploy a Quarkus native image on Azure with the telemetry enabled? Would you have any feedback to share?

**Comment by melloware** [comment]
I have not yet @jeanbisutti what issue are you having?  Are you getting an error?  StackTrace?

**Comment by jeanbisutti** [comment]
@melloware I'm not having a problem. I was curious if you tried it and what you thought.

**Comment by melloware** [comment]
Oh nope not yet the Azure Quarkus project i was working on got pushed the back by the client.  i was doing everything with Jaeger OpenTelemetry while waiting on this Azure Insights support!
