### ISSUE TITLE
Error deploying Cloud Run with gcp exporter

### ISSUE THREAD

**Issue by marcusricardoaguiar** [quarkiverse/quarkus-opentelemetry-exporter#83]
Hi,

I've been trying to deploy a cloud run instance with the gcp exporter but I'm getting the following issue:
`[io.ope.sdk.tra.exp.SimpleSpanProcessor] (vert.x-eventloop-thread-0) Exporter threw an Exception: com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Failed computing credential metadata`

These are the packages I've been using:
```
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkiverse.opentelemetry.exporter</groupId>
      <artifactId>quarkus-opentelemetry-exporter-gcp</artifactId>
      <version>2.0.0.Final</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-container-image-jib</artifactId>
    </dependency>
  </dependencies>
```

And I've defined the following parameters:
```
quarkus.opentelemetry.tracer.exporter.gcp.enabled = true
quarkus.opentelemetry.tracer.exporter.gcp.projectid = "test"
quarkus.opentelemetry.tracer.exporter.gcp.cloudrun = true
quarkus.opentelemetry.tracer.exporter.otlp.enabled = false
```

Is there any dependency package I have to add or any parameter that is missing.

**Comment by t0xa** [comment]
Hello,

I've noticed that the GCP's Project ID set to `test`. Do you really have such project?

If you are deploying your code directly to GCP, you can skip this property. It's only useful for local testing. The project name is set by CloudRun infra.

Hope this helps

**Comment by marcusricardoaguiar** [comment]
> Hello,
> 
> I've noticed that the GCP's Project ID set to `test`. Do you really have such project?
> 
> If you are deploying your code directly to GCP, you can skip this property. It's only useful for local testing. The project name is set by CloudRun infra.
> 
> Hope this helps

Hi @t0xa , Yes. I've deployed it in GCP directly. I've also tried without this parameter and I'm also getting the same issue. Any idea what might be happening? Is there a specific quarkus version that I must use to make it work properly?

**Comment by t0xa** [comment]
Hi @marcusricardoaguiar 

I've just tried to create sample project via the https://code.quarkus.io/ and deployed it to new project in GCP. It works as expected. 

- What are the quarkus versions you are using?
- Are you using any other GCP libraries in the pom?
- Does the Cloud Run service account in the IAM section have custom roles/permissions, or is it just an Editor.

**Comment by marcusricardoaguiar** [comment]
> Hi @marcusricardoaguiar
> 
> I've just tried to create sample project via the https://code.quarkus.io/ and deployed it to new project in GCP. It works as expected.
> 
> * What are the quarkus versions you are using?
> * Are you using any other GCP libraries in the pom?
> * Does the Cloud Run service account in the IAM section have custom roles/permissions, or is it just an Editor.

Hi @t0xa , I've just tried using the sample project you've shared and it still shows the issue. Just to clarify, I was able to deploy the application, but when I try to hit `/hello` endpoint it shows the warning error when trying to export the traces:
![image](https://github.com/quarkiverse/quarkus-opentelemetry-exporter/assets/8216333/5d8213a6-96fd-4654-a79a-e5417ffcbb0f)

Don't you see any of these issues on your logs? Thanks!

**Comment by t0xa** [comment]
Hi,

Could you please check you IAM settings. What are the permissions for `xxxxxx-compute@developer.gserviceaccount.com` principal?

Do you have billing connected and enabled for your project?

How are you building the docker image? Quarkus maven plugin?

**Comment by t0xa** [comment]
One of the differences I see, is that you are building native image. Could you please try to build standard image?

**Comment by marcusricardoaguiar** [comment]
> One of the differences I see, is that you are building native image. Could you please try to build standard image?

Hi @t0xa, I was able to make it work just changing the mvn command to build/push the image:
```
 mvn package \
 	-DskipTests \
 	-Dquarkus.native.remote-container-build=true \
 	-Dquarkus.container-image.build=true \
 	-Dquarkus.container-image.registry="****" \
 	-Dquarkus.container-image.group="*****" \
 	-Dquarkus.container-image.tag=v1 \
 	-Dquarkus.container-image.name=hello-world \
 	-Dquarkus.container-image.push=true
```

Thank you so much!!!

**Comment by t0xa** [comment]
No problem, but it looks like the native image doesn't work :(

I will try.

**Comment by marcusricardoaguiar** [comment]
> No problem, but it looks like the native image doesn't work :(
> 
> I will try to reproduce and fix this.

Hi @t0xa , do you have news about this issue? Let me know if you need help testing this one. Thanks!

**Comment by brunobat** [comment]
We have a fix for the native image but we are stuck in a GraalVM bug now.
